# Pandas Merge

In [1]:
import pandas as pd
import numpy as np

In [2]:
cust = pd.read_csv('Customer.csv')
ord = pd.read_csv('Orders.csv')

display(cust.head())
display(ord.head())

customer_id        name      city signup_date
0            1  Customer_1  Surabaya  2023-01-01
1            2  Customer_2   Bandung  2023-01-16
2            3  Customer_3     Medan  2023-01-31
3            4  Customer_4   Jakarta  2023-02-15
4            5  Customer_5  Surabaya  2023-03-02

order_id  customer_id    product   amount  order_date
0       101            5      Mouse  3000714  2023-03-01
1       102            6      Mouse  3197421  2023-03-06
2       103           18   Keyboard  2948757  2023-03-11
3       104            9  Headphone   540837  2023-03-16
4       105            7     Laptop  3470231  2023-03-21

In [9]:
# Merge dengan inner join
ord_cust = pd.merge(ord, cust, how='inner', on='customer_id')
ord_cust[['order_id', 'customer_id', 'name', 'city', 'product', 'amount']].head()

order_id  customer_id         name      city    product   amount
0       101            5   Customer_5  Surabaya      Mouse  3000714
1       102            6   Customer_6  Surabaya      Mouse  3197421
2       103           18  Customer_18     Medan   Keyboard  2948757
3       104            9   Customer_9   Jakarta  Headphone   540837
4       105            7   Customer_7       BSD     Laptop  3470231

In [10]:
# .join fuction menggabungkan dua dataframe berdasarkan indexnya, jika ada kolom yang sama, maka akan ditambahkan suffix _x dan _y
# df1.join(df2, lsuffix='_x', rsuffix='_y')
cust_new = cust.set_index('customer_id')
ord_new = ord.set_index('customer_id')
ord_cust_join = ord_new.join(cust_new, lsuffix='_left', rsuffix='_right')
ord_cust_join[['order_id', 'name', 'city', 'product', 'amount']].head()

order_id         name      city    product   amount
customer_id                                                     
5                 101   Customer_5  Surabaya      Mouse  3000714
6                 102   Customer_6  Surabaya      Mouse  3197421
18                103  Customer_18     Medan   Keyboard  2948757
9                 104   Customer_9   Jakarta  Headphone   540837
7                 105   Customer_7       BSD     Laptop  3470231

In [12]:
# menggunakan lsuffix dan rsuffix untuk menghindari duplikasi nama kolom
cust.join(ord, lsuffix='_left', rsuffix='_right').head()

customer_id_left        name      city signup_date  order_id  \
0                 1  Customer_1  Surabaya  2023-01-01       101   
1                 2  Customer_2   Bandung  2023-01-16       102   
2                 3  Customer_3     Medan  2023-01-31       103   
3                 4  Customer_4   Jakarta  2023-02-15       104   
4                 5  Customer_5  Surabaya  2023-03-02       105   

   customer_id_right    product   amount  order_date  
0                  5      Mouse  3000714  2023-03-01  
1                  6      Mouse  3197421  2023-03-06  
2                 18   Keyboard  2948757  2023-03-11  
3                  9  Headphone   540837  2023-03-16  
4                  7     Laptop  3470231  2023-03-21

# Latihan Soal

## Nomor 1

In [ ]:
mulai = int(input("Mulai: "))
selesai = int(input("Selesai: "))

arr = np.arange(mulai, selesai)   
print("# 1 Dimensi")
print(arr)

arr2d = arr.reshape(3, 9)
print("\n# 2 Dimensi")
print(arr2d)

arr3d = arr.reshape(3, 3, 3)
print("\n# 3 Dimensi")
print(arr3d)


# 1 Dimensi
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]

# 2 Dimensi
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]

# 3 Dimensi
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


## Nomor 2

In [41]:
n = int(input("Banyak Data: "))      #  16
mulai = int(input("Mulai: "))        #  1
selesai = int(input("Selesai: "))    #  50

arr1d = np.random.randint(mulai, selesai+1, n)
print("# Array 1 Dimensi")
print(arr1d)

arr2d = arr1d.reshape(-1, 4) 
print("\n# Array 2 Dimensi")
print(arr2d)

arr2d_flip = arr2d[:, ::-1]
print("\n# Tukar Posisi Tiap Baris")
print(arr2d_flip)


# Array 1 Dimensi
[25 38  1 17 27 47 41 18 50 40 33 44 13 12  8 24]

# Array 2 Dimensi
[[25 38  1 17]
 [27 47 41 18]
 [50 40 33 44]
 [13 12  8 24]]

# Tukar Posisi Tiap Baris
[[17  1 38 25]
 [18 41 47 27]
 [44 33 40 50]
 [24  8 12 13]]


## Nomor 3

In [ ]:
arr = np.zeros((10, 10))

arr[0, :] = 4      # b atas
arr[-1, :] = 4     # b bawah
arr[:, 0] = 4      # k kiri
arr[:, -1] = 4     # k kanan

print(arr)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]


## Nomor 4

In [20]:
data = list(range(1, 27))

index = [chr(i) for i in range(97, 123)]

series = pd.Series(data, index=index)

print(series)


a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64


## Nomor 5

In [ ]:
series = pd.Series(np.random.randint(1, 6, 100))
print("# Series Random")
print(series)

freq = series.value_counts()
print("\n# Frekuensi Setiap Angka")
print(freq)

top2 = freq.head(2)
print("\n# 2 Angka dengan Frekuensi Tertinggi")
print(top2)

'# Series Random'

0     3
1     4
2     1
3     4
4     1
     ..
95    5
96    3
97    4
98    5
99    1
Length: 100, dtype: int32

'\n# Frekuensi Setiap Angka'

5    28
4    25
1    18
3    16
2    13
Name: count, dtype: int64

'\n# 2 Angka dengan Frekuensi Tertinggi'

5    28
4    25
Name: count, dtype: int64

## Nomor 6

In [48]:
import seaborn as sns

mpg = sns.load_dataset('mpg')
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [49]:
mpg.describe(exclude=['number'])

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [50]:
mpg.columns


Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [51]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

## Nomor 7

In [30]:
missing_hp = mpg[mpg['horsepower'].isnull()]
print("# Data Missing Value pada 'horsepower'")
display(missing_hp)

# Data Missing Value pada 'horsepower'


mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [31]:
print("\n# Index Lokasi Missing Value pada 'horsepower'")
print(mpg[mpg['horsepower'].isnull()].index)


# Index Lokasi Missing Value pada 'horsepower'
Index([32, 126, 330, 336, 354, 374], dtype='int64')


## Nomor 8

In [33]:
display(mpg)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [55]:
mean_hp_by_origin = mpg.groupby('origin')['horsepower'].mean()
print(mean_hp_by_origin)


origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64


## Nomor 9

In [38]:
mpg['horse_origin'] = np.where(
    mpg['horsepower'] < 105, 
    'lower ' + mpg['origin'], 
    'upper ' + mpg['origin']
)

mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite     upper usa  
3            70     usa              amc rebel sst     upper usa  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage     lower usa  
396          82     usa                ford ranger     lower usa  
397          82     usa                 chevy s-10     lower usa  

[398 rows x 10 columns]

## Nomor 10

In [39]:
grouped_weight = (
    mpg.groupby('origin')['weight']
       .agg(['mean', 'std', 'sum', 'count', 'min', 'max'])
       .reset_index()
)


display(grouped_weight)

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140

# Latihan Soal 2